#!/bin/sh /etc/rc.common

START=99

DNSFORWARDER_CONF=/etc/dnsforwarder.conf
PID_FILE=/var/run/dnsforwarder.pid

chkpid(){
    pid=$1
    [ -z "$pid" ] && return 1
    [ ! -d /proc/$pid ] && return 1
    return 0
}

start(){
	pid=`ps|awk '$5 ~ /\[dnsforwarder\]/ {print $1}'`
	if chkpid $pid; then
		echo "dnsforwarder running at: $pid";
		return 0
	else
		dnsforwarder -f $DNSFORWARDER_CONF -d > /dev/null
		usleep 50000
	fi
	pid=`ps|awk '$5 ~ /\[dnsforwarder\]/ {print $1}'`
	if chkpid $pid; then
		echo "dnsforwarder running at: $pid"
		echo $pid > $PID_FILE
		return 0
	else
		echo "dnsforwarder startup failed!"
		return 1
	fi
}

stop(){
	if [ ! -e $PID_FILE ]; then
		echo "dnsforwarder not running"
		return 1
	fi
	pid=`cat $PID_FILE`
	if [ -z "$pid" ]; then
		echo "dnsforwarder not running"
		return 1
	fi
	if chkpid $pid; then
		kill -9 $pid>/dev/null
		usleep 50000
	else
		echo "dnsforwarder not running"
		return 1
	fi
	if chkpid $pid; then
		echo "can't kill dnsforwarder pid: $pid!"
		return 1
	else
		echo "killed dnsforwarder pid: $pid!"
	fi
    rm -f $PID_FILE
    return 0
}
