#!/bin/sh /etc/rc.common

START=99

DNSFORWARDER_CONF=/etc/dnsforwarder/dnsforwarder.conf
PID_FILE=/var/run/dnsforwarder.pid

chkpid(){
    pid=$1
    [ -z "$pid" ] && return 1
    [ ! -d /proc/$pid ] && return 1
    return 0
}

start(){
	dnsforwarder -f $DNSFORWARDER_CONF -d
	usleep 50000
	pid=`ps|awk '$5 ~ /\[dnsforwarder\]/ {print $1}'`
	chkpid $pid && echo $pid > $PID_FILE || echo "dnsforwarder startup failed!"
}

stop(){
	[ -e $PID_FILE ] || return 1
	pid=`cat $PID_FILE`
	[ -z "$pid" ] && return 1
	if chkpid $pid; then
        kill -9 $pid
		usleep 50000
		if chkpid $pid; then
			echo "can't kill dnsforwarder pid: $pid!"
			exit 1
		else
			echo "killed dnsforwarder pid: $pid!"
		fi
    fi
    rm -f $PID_FILE
    return 0
}
